const explorationImages={"golf-silent.mp4":["/assets/popupGolf-img00961.webp","/assets/popupGolf-imgBrandingFilm91.webp","/assets/popupGolf-imgBrandingFilm61.webp","/assets/popupGolf-imgBrandingFilm7.webp","/assets/popupGolf-imgBrandingFilm61.webp","/assets/popupGolf-imgBrandingFilm81.webp","/assets/popupGolf-imgBrandingFilmDark61.webp","/assets/popupGolf-imgBrandingFilmDark22.webp","/assets/popupGolf-imgBrandingFilmDark131.webp"],"data-silent.mp4":["/assets/popupData-imgImage1112539.webp","/assets/popupData-imgImage1112542.webp","/assets/popupData-imgFlow11.webp","/assets/popupData-imgFlow21.webp"],"landscape-silent.mp4":["/assets/popupLandscape-img09.webp","/assets/popupLandscape-img08.webp","/assets/popupLandscape-img07.webp","/assets/popupLandscape-img06.webp","/assets/popupLandscape-img05.webp","/assets/popupLandscape-img04.webp","/assets/popupLandscape-img03.webp","/assets/popupLandscape-img1024.webp","/assets/popupLandscape-img02.webp","/assets/popupLandscape-img01.webp"]};
const menu=document.querySelector('.menu-toggle');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));document.querySelector('#site-menu').classList.toggle('open',open);});
const topLink=document.querySelector('.back-top');addEventListener('scroll',()=>topLink?.classList.toggle('visible',scrollY>600),{passive:true});
const sectionLinks=[...document.querySelectorAll('.case-nav a')];
if(sectionLinks.length){const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){sectionLinks.forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id));}},{rootMargin:'-10% 0px -70% 0px'});sectionLinks.forEach(a=>{const el=document.querySelector(a.hash);if(el)observer.observe(el);});}
// Fixed diagrams retain their internal geometry; surrounding article copy reflows.
function sizeMedia(){document.querySelectorAll('.media-scaler').forEach(w=>{const c=w.firstElementChild,n=+w.dataset.designWidth;const ratio=Math.min(1,w.clientWidth/n);c.style.transform=`scale(${ratio})`;w.style.height=(c.offsetHeight*ratio)+'px';});document.querySelectorAll('.project-thumb').forEach(w=>{const ratio=w.clientWidth/540;const c=w.querySelector('.thumbnail-canvas');if(c){c.style.transform=`scale(${ratio})`;}});}
const ro=new ResizeObserver(sizeMedia);document.querySelectorAll('.media-scaler,.project-thumb').forEach(w=>ro.observe(w));document.fonts.ready.then(sizeMedia);addEventListener('load',sizeMedia);sizeMedia();
const dialog=document.querySelector('#film-dialog');let opener;
document.querySelectorAll('[data-film]').forEach(card=>{card.addEventListener('click',()=>{opener=card;const scene=card.lastElementChild.textContent;const images=explorationImages[(card.dataset.video||'').split('/').pop()];dialog.classList.toggle('exploration-dialog',!!images);dialog.classList.toggle('portrait-exploration',!!images&&/data-silent|landscape-silent/.test(card.dataset.video));dialog.querySelector('#film-title').textContent=images?'Rendering Explorations':scene;dialog.querySelector('.exploration-intro')?.remove();dialog.querySelector('.exploration-gallery')?.remove();if(images){const intro=document.createElement('p');intro.className='exploration-intro';intro.textContent='Exploring color, lighting, and materials through multiple render iterations to refine the final look and feel.';dialog.querySelector('#film-title').after(intro);const gallery=document.createElement('div');gallery.className='exploration-gallery';gallery.tabIndex=0;gallery.setAttribute('role','region');gallery.setAttribute('aria-label',scene+' render iterations. Scroll horizontally.');for(const[srcIndex,src]of images.entries()){const img=document.createElement('img');img.src=src;img.alt=scene+' — exploration '+(srcIndex+1);img.width=172;img.height=306;img.draggable=false;if(card.dataset.video.includes('landscape-silent')&&[3,4,5,6,8,9].includes(srcIndex))img.style.opacity='.8';gallery.append(img);}gallery.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();gallery.scrollBy({left:e.key==='ArrowRight'?182:-182,behavior:'smooth'});}});dialog.querySelector('.dialog-media').after(gallery);}const media=dialog.querySelector('.dialog-media');media.replaceChildren();const source=card.dataset.video;if(source){const video=document.createElement('video');video.src=source;video.controls=true;video.autoplay=true;video.muted=card.dataset.sound!=="true";video.defaultMuted=video.muted;video.playsInline=true;media.append(video);dialog.querySelector('.film-status').hidden=true;}else{const img=card.querySelector('img').cloneNode();media.append(img);dialog.querySelector('.film-status').hidden=false;}dialog.showModal();dialog.querySelector("video")?.play().catch(()=>{});dialog.scrollTop=0;});});
function closeFilm(){dialog.querySelector('video')?.pause();dialog.close();opener?.focus();}dialog?.querySelector('.dialog-close').addEventListener('click',closeFilm);dialog?.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeFilm();}});dialog?.addEventListener('close',()=>dialog.querySelector('video')?.pause());
// Film cards open a player; playback and audio are controlled by its buttons.
for(const v of document.querySelectorAll('.film-media video')){v.addEventListener('playing',()=>v.classList.add('playing'));v.addEventListener('pause',()=>v.classList.remove('playing'));v.addEventListener('error',()=>v.classList.remove('playing'));}
// Native buttons exclusively control playback and audio; pointer movement has no effect.
for(const v of document.querySelectorAll('.project-video video')){v.controls=true;v.autoplay=false;v.muted=v.dataset.sound!=='true';v.defaultMuted=v.muted;}
function sizeExact(){document.querySelectorAll('.exact-viewport').forEach(w=>{if(w.hidden)return;const c=w.firstElementChild;if(!c)return;const scale=Math.min(1,w.clientWidth/Number(w.dataset.designWidth));c.style.transform=`scale(${scale})`;w.style.height=`${c.offsetHeight*scale}px`;});}
const exactResize=new ResizeObserver(sizeExact);document.querySelectorAll('.exact-viewport').forEach(w=>exactResize.observe(w));document.fonts.ready.then(sizeExact);addEventListener('load',sizeExact);sizeExact();
for(const rail of document.querySelectorAll('.interview-gallery')){let startX=0,startScroll=0,dragging=false;rail.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;dragging=true;startX=e.clientX;startScroll=rail.scrollLeft;rail.setPointerCapture(e.pointerId);rail.classList.add('dragging');});rail.addEventListener('pointermove',e=>{if(dragging){rail.scrollLeft=startScroll-(e.clientX-startX);e.preventDefault();}});const end=()=>{dragging=false;rail.classList.remove('dragging');};rail.addEventListener('pointerup',end);rail.addEventListener('pointercancel',end);rail.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();rail.scrollBy({left:(e.key==='ArrowRight'?1:-1)*336,behavior:'smooth'});}});}
for(const group of document.querySelectorAll('.iteration-sequence')){const steps=[...group.querySelectorAll('.iteration-step')],slides=[...group.querySelectorAll('.iteration-slide')];let current=0,inView=false,paused=matchMedia('(prefers-reduced-motion:reduce)').matches;const toggle=document.createElement('button');toggle.className='iteration-toggle';toggle.textContent=paused?'Play animation':'Pause animation';toggle.setAttribute('aria-label','Pause or resume design process animation');group.append(toggle);const select=i=>{current=i;steps.forEach((s,j)=>{s.classList.toggle('is-active',j===i);s.setAttribute('aria-pressed',String(j===i));});slides.forEach((s,j)=>s.hidden=j!==i);sizeExact();};let last=Date.now();for(const [i,s]of steps.entries()){s.addEventListener('click',()=>{select(i);last=Date.now();});s.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(i);last=Date.now();}});}toggle.addEventListener('click',()=>{paused=!paused;toggle.textContent=paused?'Play animation':'Pause animation';last=Date.now();});new IntersectionObserver(es=>{inView=es[0].isIntersecting;last=Date.now();},{threshold:.15}).observe(group);setInterval(()=>{if(inView&&!paused&&!document.hidden&&Date.now()-last>=2000){select((current+1)%steps.length);last=Date.now();}},200);select(0);}
// Slowly pan the interview photos while they are visible, preserving manual scrolling.
for(const gallery of document.querySelectorAll('.interview-gallery')){
  const reduced=matchMedia('(prefers-reduced-motion:reduce)');
  let visible=false,hovered=false,focused=false,pressed=false,paused=reduced.matches,direction=1,last=0,position=gallery.scrollLeft,resumeAt=0;
  const control=document.createElement('button');control.className='gallery-motion-toggle';control.type='button';
  const label=()=>{control.textContent=paused?'▶':'Ⅱ';control.setAttribute('aria-label',paused?'Play photo scrolling':'Pause photo scrolling');control.setAttribute('title',paused?'Play photo scrolling':'Pause photo scrolling');};
  label();gallery.parentElement.append(control);gallery.classList.add('auto-pan');
  control.addEventListener('click',()=>{paused=!paused;position=gallery.scrollLeft;label();});
  gallery.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')hovered=true;});gallery.addEventListener('pointerleave',()=>{hovered=false;position=gallery.scrollLeft;});
  gallery.addEventListener('focusin',()=>focused=true);gallery.addEventListener('focusout',()=>{focused=false;position=gallery.scrollLeft;});
  gallery.addEventListener('pointerdown',()=>pressed=true);const release=()=>{pressed=false;position=gallery.scrollLeft;resumeAt=performance.now()+2000;};gallery.addEventListener('pointerup',release);gallery.addEventListener('pointercancel',release);
  gallery.addEventListener('wheel',()=>{resumeAt=performance.now()+2500;position=gallery.scrollLeft;},{passive:true});gallery.addEventListener('scroll',()=>{if(hovered||focused||pressed||paused||performance.now()<resumeAt)position=gallery.scrollLeft;},{passive:true});
  new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;position=gallery.scrollLeft;last=0;},{threshold:.1}).observe(gallery);
  function pan(now){const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(visible&&!document.hidden&&!hovered&&!focused&&!pressed&&!paused&&now>=resumeAt){const max=gallery.scrollWidth-gallery.clientWidth;if(max>1){position=Math.max(0,Math.min(max,position+direction*22*dt));gallery.scrollLeft=position;if(position>=max){direction=-1;resumeAt=now+800;}else if(position<=0){direction=1;resumeAt=now+800;}}}requestAnimationFrame(pan);}requestAnimationFrame(pan);
}
